"use client";

import { useEffect, useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { Textarea } from "@/components/ui/textarea";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import { api, formatDateTime, type Account, type DayPlan, type PlanScenario, type Setup } from "@/lib/tradesync/api";

const dayIn = (timezone: string) => new Intl.DateTimeFormat("en-CA", { timeZone: timezone, year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
const empty = (accountId: number, timezone: string, date = dayIn(timezone)): Omit<DayPlan, "id" | "updated_at"> => ({ account_id: accountId, plan_date: date, timezone, mode: "observe", status: "draft", revision: 0, self_state: "", market_view: "", events: "", risk_limit: "", stop_conditions: "", improvement_focus: "", waiting_condition: "", no_trade_reason: "等待符合模型的机会", allowed_playbook_version_ids: [], scenarios: [], first_confirmed_at: null, confirmed_at: null, confirmed_late: false });

export function DailyPlan({ accounts, timezone }: { accounts: Account[]; timezone: string }) {
  const [accountId, setAccountId] = useState(Number(accounts[0]?.id ?? 0)); const [date, setDate] = useState(dayIn(timezone));
  const [plan, setPlan] = useState<Omit<DayPlan, "id" | "updated_at"> | DayPlan>(empty(accountId, timezone)); const [setups, setSetups] = useState<Setup[]>([]);
  const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const versions = setups.filter(s => s.status === "active" && s.latest_published).map(s => ({ setup: s, version: s.latest_published! }));
  useEffect(() => { api.setups().then(setSetups).catch(() => setSetups([])); }, []);
  useEffect(() => { if (!accountId) return; let active = true; setLoading(true); setError(""); api.dayPlan(accountId, date).then(value => { if (active) setPlan(value ?? empty(accountId, timezone, date)); }).catch(e => { if (active) setError(e instanceof Error ? e.message : "日计划读取失败"); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [accountId, date, timezone]);
  function patch(value: Partial<DayPlan>) { setPlan({ ...plan, ...value }); }
  function addScenario() { patch({ scenarios: [...plan.scenarios, { id: `scenario_${Date.now()}`, name: "", symbol: "", direction: "neutral", playbook_version_id: null, area: "", confirmation: "", invalidation: "", exit_principle: "", session: "" }] }); }
  function scenario(index: number, value: Partial<PlanScenario>) { patch({ scenarios: plan.scenarios.map((item, i) => i === index ? { ...item, ...value } : item) }); }
  async function save() { setSaving(true); setError(""); try { const value = await api.saveDayPlan({
    expected_revision: plan.revision, account_id: accountId, plan_date: date, timezone: plan.timezone, mode: plan.mode,
    self_state: plan.self_state, market_view: plan.market_view, events: plan.events, risk_limit: plan.risk_limit,
    stop_conditions: plan.stop_conditions, improvement_focus: plan.improvement_focus, waiting_condition: plan.waiting_condition,
    no_trade_reason: plan.no_trade_reason, allowed_playbook_version_ids: plan.allowed_playbook_version_ids,
    scenarios: plan.scenarios, change_reason: plan.status === "confirmed" ? "盘中根据最新判断修订" : "",
  }); setPlan(value); window.dispatchEvent(new Event("tradesync-plan-changed")); } catch (e) { setError(e instanceof Error ? e.message : "计划保存失败"); } finally { setSaving(false); } }
  async function confirm() { if (!("id" in plan)) return; setSaving(true); setError(""); try { setPlan(await api.confirmDayPlan(plan.id, plan.revision)); window.dispatchEvent(new Event("tradesync-plan-changed")); } catch (e) { setError(e instanceof Error ? e.message : "计划确认失败"); } finally { setSaving(false); } }
  if (!accounts.length) return null;
  return <Card><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle>盘前日计划</CardTitle><CardDescription>记录当时判断和风险边界；确认后修订会保留版本。</CardDescription></div><div className="flex gap-2"><Badge variant={plan.status === "confirmed" ? "default" : "secondary"}>{plan.status === "confirmed" ? "已确认" : "草稿"}</Badge>{plan.confirmed_late && <Badge variant="destructive">晚于首笔交易</Badge>}</div></div></CardHeader><CardContent className="space-y-5">
    <FieldGroup className="sm:flex-row sm:flex-wrap"><Field className="sm:w-auto"><FieldLabel htmlFor="plan-account">账户</FieldLabel><NativeSelect id="plan-account" value={accountId} onChange={e => setAccountId(Number(e.target.value))}>{accounts.map(a => <NativeSelectOption key={a.id} value={a.id}>{a.label || a.mt5_login}</NativeSelectOption>)}</NativeSelect></Field><Field className="sm:w-auto"><FieldLabel htmlFor="plan-date">计划日期</FieldLabel><Input id="plan-date" type="date" value={date} onChange={e => setDate(e.target.value)} /></Field><Field className="sm:w-auto"><FieldLabel>时区</FieldLabel><Input value={plan.timezone} readOnly /></Field></FieldGroup>
    <Field><FieldLabel>今日状态</FieldLabel><ToggleGroup type="single" variant="outline" value={plan.mode} onValueChange={value => value && patch({ mode: value as DayPlan["mode"], no_trade_reason: value === "trade" ? "" : plan.no_trade_reason || "等待符合模型的机会" })}><ToggleGroupItem value="trade">准备交易</ToggleGroupItem><ToggleGroupItem value="observe">仅观察</ToggleGroupItem><ToggleGroupItem value="rest">休息</ToggleGroupItem></ToggleGroup></Field>
    <FieldGroup><Field><FieldLabel htmlFor="plan-state">自身状态</FieldLabel><Textarea id="plan-state" value={plan.self_state} onChange={e => patch({ self_state: e.target.value })} placeholder="精力、情绪、可用时间" /></Field><Field><FieldLabel htmlFor="plan-market">市场判断</FieldLabel><Textarea id="plan-market" value={plan.market_view} onChange={e => patch({ market_view: e.target.value })} placeholder="结构、重要周期和判断依据；不确定时如实记录" /></Field><Field><FieldLabel htmlFor="plan-events">事件安排</FieldLabel><Textarea id="plan-events" value={plan.events} onChange={e => patch({ events: e.target.value })} placeholder="事件时间、回避区间，或明确尚未核对" /></Field></FieldGroup>
    {plan.mode === "trade" ? <><Field><FieldLabel>今日允许模型</FieldLabel><div className="flex flex-wrap gap-3">{versions.length ? versions.map(({ setup, version }) => <label key={version.id} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><Checkbox checked={plan.allowed_playbook_version_ids.includes(version.id)} onCheckedChange={checked => patch({ allowed_playbook_version_ids: checked ? [...plan.allowed_playbook_version_ids, version.id] : plan.allowed_playbook_version_ids.filter(id => id !== version.id) })} />{setup.name} · v{version.version}</label>) : <p className="text-muted-foreground text-sm">尚无已发布 Playbook，请先在“模型与规则”中发布。</p>}</div></Field>
      <FieldGroup className="sm:grid sm:grid-cols-2"><Field><FieldLabel htmlFor="plan-risk">风险边界</FieldLabel><Textarea id="plan-risk" value={plan.risk_limit} onChange={e => patch({ risk_limit: e.target.value })} placeholder="风险金额、交易次数等；未设置时明确填写未设定" /></Field><Field><FieldLabel htmlFor="plan-stop">停止条件</FieldLabel><Textarea id="plan-stop" value={plan.stop_conditions} onChange={e => patch({ stop_conditions: e.target.value })} /></Field><Field><FieldLabel htmlFor="plan-wait">等待条件</FieldLabel><Textarea id="plan-wait" value={plan.waiting_condition} onChange={e => patch({ waiting_condition: e.target.value })} /></Field><Field><FieldLabel htmlFor="plan-focus">今日改进重点</FieldLabel><Textarea id="plan-focus" value={plan.improvement_focus} onChange={e => patch({ improvement_focus: e.target.value })} /></Field></FieldGroup>
      <div className="space-y-3"><div className="flex items-center justify-between"><div><h3 className="font-medium">候选场景</h3><p className="text-muted-foreground text-xs">场景不是下单指令，只记录满足条件后才考虑执行的判断。</p></div><Button variant="outline" size="sm" onClick={addScenario}><Plus />添加场景</Button></div>{plan.scenarios.map((item, index) => <div key={item.id} className="space-y-3 rounded-lg border p-4"><div className="grid gap-3 sm:grid-cols-3"><Field><FieldLabel>场景名称</FieldLabel><Input value={item.name} onChange={e => scenario(index, { name: e.target.value })} /></Field><Field><FieldLabel>品种</FieldLabel><Input value={item.symbol} onChange={e => scenario(index, { symbol: e.target.value.toUpperCase() })} /></Field><Field><FieldLabel>方向倾向</FieldLabel><NativeSelect className="w-full" value={item.direction} onChange={e => scenario(index, { direction: e.target.value as PlanScenario["direction"] })}><NativeSelectOption value="buy">做多</NativeSelectOption><NativeSelectOption value="sell">做空</NativeSelectOption><NativeSelectOption value="neutral">中性等待</NativeSelectOption></NativeSelect></Field></div><Field><FieldLabel>关联模型</FieldLabel><NativeSelect className="w-full" value={item.playbook_version_id ?? ""} onChange={e => scenario(index, { playbook_version_id: e.target.value ? Number(e.target.value) : null })}><NativeSelectOption value="">暂不关联</NativeSelectOption>{versions.map(({ setup, version }) => <NativeSelectOption key={version.id} value={version.id}>{setup.name} · v{version.version}</NativeSelectOption>)}</NativeSelect></Field><div className="grid gap-3 sm:grid-cols-2"><Field><FieldLabel>关注区域</FieldLabel><Textarea value={item.area} onChange={e => scenario(index, { area: e.target.value })} /></Field><Field><FieldLabel>入场确认</FieldLabel><Textarea value={item.confirmation} onChange={e => scenario(index, { confirmation: e.target.value })} /></Field><Field><FieldLabel>逻辑失效</FieldLabel><Textarea value={item.invalidation} onChange={e => scenario(index, { invalidation: e.target.value })} /></Field><Field><FieldLabel>退出原则</FieldLabel><Textarea value={item.exit_principle} onChange={e => scenario(index, { exit_principle: e.target.value })} /></Field></div><Button variant="ghost" size="sm" onClick={() => patch({ scenarios: plan.scenarios.filter((_, i) => i !== index) })}><Trash2 />移除场景</Button></div>)}</div></> : <Field><FieldLabel htmlFor="plan-no-trade">{plan.mode === "rest" ? "休息原因" : "仅观察原因"}</FieldLabel><Textarea id="plan-no-trade" value={plan.no_trade_reason} onChange={e => patch({ no_trade_reason: e.target.value })} /></Field>}
    {plan.confirmed_at && <p className="text-muted-foreground text-xs">最近确认：{formatDateTime(plan.confirmed_at)}；首次确认时间保持不变。</p>}{error && <Alert variant="destructive"><AlertTitle>日计划未保存</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}
    <div className="grid gap-2 sm:grid-cols-2"><Button variant="outline" disabled={saving || loading} onClick={save}>{saving ? "正在保存…" : plan.status === "confirmed" ? "保存为修订草稿" : "保存草稿"}</Button><Button disabled={saving || loading || !("id" in plan) || plan.status === "confirmed"} onClick={confirm}>确认今日计划</Button></div>
  </CardContent></Card>;
}
