"use client";

import { useEffect, useState } from "react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { Textarea } from "@/components/ui/textarea";
import { api, formatDateTime, formatUnix, type Account, type IntentionCandidate, type IntentionState, type PlanScenario, type TradeIntention } from "@/lib/tradesync/api";

const labels: Record<IntentionState, string> = { watching: "观察中", prepared: "准备执行", executed_unlinked: "已执行待关联", linked: "已关联", abandoned: "主动放弃", invalidated: "条件失效", expired: "到期未执行" };

export function Intentions({ accounts, timezone }: { accounts: Account[]; timezone: string }) {
  const [accountId, setAccountId] = useState(Number(accounts[0]?.id ?? 0)); const [date, setDate] = useState(new Intl.DateTimeFormat("en-CA", { timeZone: timezone, year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date()));
  const [planId, setPlanId] = useState<number | null>(null); const [scenarios, setScenarios] = useState<PlanScenario[]>([]); const [items, setItems] = useState<TradeIntention[]>([]);
  const [scenarioId, setScenarioId] = useState(""); const [symbol, setSymbol] = useState(""); const [direction, setDirection] = useState<"buy" | "sell">("buy"); const [state, setState] = useState<"watching" | "prepared">("watching"); const [basis, setBasis] = useState(""); const [risk, setRisk] = useState("");
  const [candidates, setCandidates] = useState<Record<number, IntentionCandidate[]>>({}); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function load() { if (!accountId) return; try { const result = await api.intentions(accountId, date); setPlanId(result.plan_id); setScenarios(result.scenarios); setItems(result.items); } catch (e) { setError(e instanceof Error ? e.message : "交易意图读取失败"); } }
  useEffect(() => { void load(); }, [accountId, date]);
  useEffect(() => { const refresh = () => { void load(); }; window.addEventListener("tradesync-plan-changed", refresh); return () => window.removeEventListener("tradesync-plan-changed", refresh); }, [accountId, date]);
  function chooseScenario(id: string) { setScenarioId(id); const item = scenarios.find(value => value.id === id); if (item) { setSymbol(item.symbol); if (item.direction !== "neutral") setDirection(item.direction); setBasis(item.confirmation); } }
  async function create() { if (!symbol.trim()) { setError("请填写品种"); return; } setBusy(true); setError(""); try { await api.createIntention({ account_id: accountId, day_plan_id: planId, scenario_id: scenarioId || null, playbook_version_id: scenarios.find(item => item.id === scenarioId)?.playbook_version_id ?? null, symbol, direction, state, entry_basis: basis, risk_plan: risk }); setSymbol(""); setBasis(""); setRisk(""); setScenarioId(""); await load(); } catch (e) { setError(e instanceof Error ? e.message : "交易意图创建失败"); } finally { setBusy(false); } }
  async function transition(id: number, next: IntentionState) { let reason = ""; if (["abandoned", "invalidated", "expired"].includes(next)) { reason = window.prompt("请填写状态变化原因")?.trim() ?? ""; if (!reason) return; } setBusy(true); try { await api.transitionIntention(id, next, reason); await load(); } catch (e) { setError(e instanceof Error ? e.message : "状态更新失败"); } finally { setBusy(false); } }
  async function showCandidates(id: number) { try { setCandidates({ ...candidates, [id]: await api.intentionCandidates(id) }); } catch (e) { setError(e instanceof Error ? e.message : "候选交易读取失败"); } }
  async function link(id: number, tradeId: number) { setBusy(true); try { await api.linkIntention(id, tradeId); await load(); } catch (e) { setError(e instanceof Error ? e.message : "关联失败"); } finally { setBusy(false); } }
  if (!accounts.length) return null;
  return <Card><CardHeader><CardTitle>交易意图</CardTitle><CardDescription>在真实交易同步前记录观察或准备执行；交易发生后再人工确认关联。</CardDescription></CardHeader><CardContent className="space-y-5">
    <FieldGroup className="sm:flex-row sm:flex-wrap"><Field className="sm:w-auto"><FieldLabel>账户</FieldLabel><NativeSelect value={accountId} onChange={e => setAccountId(Number(e.target.value))}>{accounts.map(a => <NativeSelectOption key={a.id} value={a.id}>{a.label || a.mt5_login}</NativeSelectOption>)}</NativeSelect></Field><Field className="sm:w-auto"><FieldLabel>日期</FieldLabel><Input type="date" value={date} onChange={e => setDate(e.target.value)} /></Field><Field className="sm:w-auto"><FieldLabel>计划场景</FieldLabel><NativeSelect value={scenarioId} onChange={e => chooseScenario(e.target.value)}><NativeSelectOption value="">不关联场景</NativeSelectOption>{scenarios.map(item => <NativeSelectOption key={item.id} value={item.id}>{item.name} · {item.symbol}</NativeSelectOption>)}</NativeSelect></Field></FieldGroup>
    <div className="grid gap-3 sm:grid-cols-3"><Field><FieldLabel>品种</FieldLabel><Input value={symbol} onChange={e => setSymbol(e.target.value.toUpperCase())} /></Field><Field><FieldLabel>方向</FieldLabel><NativeSelect className="w-full" value={direction} onChange={e => setDirection(e.target.value as "buy" | "sell")}><NativeSelectOption value="buy">做多</NativeSelectOption><NativeSelectOption value="sell">做空</NativeSelectOption></NativeSelect></Field><Field><FieldLabel>初始状态</FieldLabel><NativeSelect className="w-full" value={state} onChange={e => setState(e.target.value as "watching" | "prepared")}><NativeSelectOption value="watching">观察候选</NativeSelectOption><NativeSelectOption value="prepared">准备执行</NativeSelectOption></NativeSelect></Field></div>
    <div className="grid gap-3 sm:grid-cols-2"><Field><FieldLabel>预期入场依据</FieldLabel><Textarea value={basis} onChange={e => setBasis(e.target.value)} /></Field><Field><FieldLabel>风险计划</FieldLabel><Textarea value={risk} onChange={e => setRisk(e.target.value)} /></Field></div><Button disabled={busy} onClick={create}>创建交易意图</Button>
    {error && <Alert variant="destructive"><AlertTitle>交易意图操作失败</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}
    <div className="space-y-3">{items.map(item => <div key={item.id} className="space-y-3 rounded-lg border p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-medium">{item.symbol} · {item.direction === "buy" ? "做多" : "做空"}</p><p className="text-muted-foreground text-xs">创建于 {formatDateTime(item.created_at)}{item.scenario_id ? " · 来自计划场景" : " · 独立意图"}</p></div><Badge>{labels[item.state]}</Badge></div><p className="whitespace-pre-wrap text-sm">入场依据：{item.entry_basis || "未填写"}</p><p className="whitespace-pre-wrap text-sm">风险计划：{item.risk_plan || "未填写"}</p>
      <div className="flex flex-wrap gap-2">{item.state === "watching" && <Button size="sm" onClick={() => transition(item.id, "prepared")}>转为准备执行</Button>}{item.state === "prepared" && <><Button size="sm" variant="outline" onClick={() => transition(item.id, "watching")}>返回观察</Button><Button size="sm" onClick={() => transition(item.id, "executed_unlinked")}>标记已执行</Button></>}{["watching", "prepared"].includes(item.state) && <><Button size="sm" variant="outline" onClick={() => transition(item.id, "abandoned")}>主动放弃</Button><Button size="sm" variant="outline" onClick={() => transition(item.id, "invalidated")}>条件失效</Button></>}{["prepared", "executed_unlinked"].includes(item.state) && <Button size="sm" variant="outline" onClick={() => showCandidates(item.id)}>查找候选交易</Button>}</div>
      {candidates[item.id] && <div className="space-y-2 rounded-md bg-muted/40 p-3">{candidates[item.id].length ? candidates[item.id].map(candidate => <div key={candidate.trade_id} className="flex flex-wrap items-center justify-between gap-2 text-sm"><span>交易 #{candidate.trade_id} · 开仓 {formatUnix(candidate.open_time)}</span><Button size="sm" disabled={busy} onClick={() => link(item.id, candidate.trade_id)}>确认关联</Button></div>) : <p className="text-muted-foreground text-sm">暂无同账户、同品种、同方向的未关联交易。</p>}</div>}
      {item.linked_trade_id && <p className="text-sm">已关联完整交易 #{item.linked_trade_id} · 关联时间 {formatDateTime(item.linked_at)}</p>}
      <details><summary className="cursor-pointer text-xs">查看状态记录</summary><div className="mt-2 space-y-1">{item.events.map(event => <p key={event.id} className="text-muted-foreground text-xs">{formatDateTime(event.created_at)} · {labels[event.to_state as IntentionState] ?? event.to_state}{event.reason ? ` · ${event.reason}` : ""}</p>)}</div></details>
    </div>)}</div>
  </CardContent></Card>;
}
