//+------------------------------------------------------------------+
//|                                       TradeSyncProbeEA.mq5       |
//|                  TradeSync API v2.1 UTC/HMAC synchronization     |
//+------------------------------------------------------------------+
#property copyright "TradeEZ"
#property version   "2.10"
#property strict

input group "TradeSync API v2.1"
input bool   Inp_EnableSync            = false;
input string Inp_ApiBaseURL            = "https://192.168.31.116:8443";
input string Inp_SecretKey             = "";   // Complete sk_live_... key generated by the web server
input int    Inp_MaxBatchSize          = 100;  // Maximum 1000; 100 is recommended
input int    Inp_HistoryDays           = 7;    // Lookback when server cursor is 0
input int    Inp_TimerSeconds          = 3;
input bool   Inp_SendSymbolSpec        = true;
input int    Inp_SnapshotIntervalSec   = 30;
input int    Inp_HeartbeatIntervalSec  = 300;

#define SYMBOL_SPEC_INTERVAL_SEC 21600
#define OPEN_LOOKBACK_DAYS       180

struct SyncDealRecord
{
   ulong  ticket;
   ulong  position_id;
   ulong  order_id;
   string symbol;
   long   entry;
   long   type;
   double volume;
   double price;
   double sl_price;
   double tp_price;
   double profit;
   double swap;
   double commission;
   long   magic;
   string comment;
   long   open_time;
   long   deal_time;
};

string   g_baseUrl = "";
long     g_gmtOffset = 0;
long     g_serverCursor = 0;
ulong    g_openPositionIds[];
long     g_openTimes[];
int      g_openMapCount = 0;
long     g_lastSymbolSendUtc = 0;
long     g_lastSnapshotUtc = 0;
long     g_lastHeartbeatUtc = 0;

int OnInit()
{
   if(!Inp_EnableSync)
   {
      Print("[TradeSync] Synchronization is disabled. Set Inp_EnableSync=true after configuring the API key.");
      return(INIT_SUCCEEDED);
   }

   if(StringLen(Inp_SecretKey) == 0)
   {
      Print("[TradeSync][ERROR] Inp_SecretKey is empty. Generate a key in the web console and paste the complete server key.");
      return(INIT_PARAMETERS_INCORRECT);
   }

   if(StringLen(Inp_ApiBaseURL) == 0)
   {
      Print("[TradeSync][ERROR] Inp_ApiBaseURL is empty.");
      return(INIT_PARAMETERS_INCORRECT);
   }

   if(Inp_MaxBatchSize < 1 || Inp_MaxBatchSize > 1000)
   {
      Print("[TradeSync][ERROR] Inp_MaxBatchSize must be between 1 and 1000.");
      return(INIT_PARAMETERS_INCORRECT);
   }

   g_baseUrl = TrimTrailingSlash(Inp_ApiBaseURL);
   EventSetTimer(MathMax(1, Inp_TimerSeconds));
   PrintFormat("[TradeSync] API v2.1 started. URL=%s batch=%d historyDays=%d", g_baseUrl, Inp_MaxBatchSize, Inp_HistoryDays);
   return(INIT_SUCCEEDED);
}

void OnDeinit(const int reason)
{
   EventKillTimer();
   PrintFormat("[TradeSync] Stopped, reason=%d", reason);
}

void OnTimer()
{
   if(!Inp_EnableSync)
      return;

   SyncDealsCycle();

   if(Inp_SendSymbolSpec)
      SendSymbolSpecsDue();

   SendSnapshotDue();
   SendHeartbeatDue();
}

void SyncDealsCycle()
{
   g_gmtOffset = (long)TimeTradeServer() - (long)TimeGMT();

   long cursor = 0;
   bool fetched = FetchLastSyncTime(cursor);
   g_serverCursor = cursor;

   if(!fetched)
      PrintFormat("[TradeSync][WARN] Cursor query failed; using local %d-day fallback for this cycle.", MathMax(1, Inp_HistoryDays));

   if(!CollectAndUploadDeals(cursor))
      Print("[TradeSync][WARN] Deal synchronization cycle did not complete; cursor was not advanced.");
}

bool FetchLastSyncTime(long &lastSyncTime)
{
   lastSyncTime = 0;
   const string body = StringFormat("{\"mt5_login\":%I64d}", GetLogin());
   string response = "";

   if(!PostJson("/api/v1/sync/last_sync_time", body, response))
      return(false);

   if(!JsonExtractLong(response, "last_sync_time", lastSyncTime))
   {
      PrintFormat("[TradeSync][ERROR] last_sync_time missing in response: %s", response);
      return(false);
   }

   PrintFormat("[TradeSync] Server cursor last_sync_time=%I64d", lastSyncTime);
   return(true);
}

bool CollectAndUploadDeals(const long cursor)
{
   const long nowUtc = (long)TimeGMT();
   const long lowerUtc = (cursor > 0) ? cursor : nowUtc - (long)MathMax(1, Inp_HistoryDays) * 86400L;
   const long mapLowerUtc = lowerUtc - (long)OPEN_LOOKBACK_DAYS * 86400L;
   const datetime toServerTime = (datetime)((long)TimeTradeServer() + 60L);

   if(!BuildOpenTimeMap((datetime)(mapLowerUtc + g_gmtOffset), toServerTime))
      return(false);

   if(!HistorySelect((datetime)(lowerUtc + g_gmtOffset), toServerTime))
   {
      PrintFormat("[TradeSync][ERROR] HistorySelect failed from=%I64d to=%I64d error=%d",
                  lowerUtc + g_gmtOffset, (long)toServerTime, GetLastError());
      return(false);
   }

   SyncDealRecord records[];
   int count = 0;
   int skippedMissingOpen = 0;
   const int total = HistoryDealsTotal();

   for(int i = 0; i < total; i++)
   {
      ulong ticket = HistoryDealGetTicket(i);
      if(ticket == 0 || !IsTradeDeal(ticket))
         continue;

      ulong positionId = (ulong)HistoryDealGetInteger(ticket, DEAL_POSITION_ID);
      if(positionId == 0)
         continue;

      long openTimeUtc = FindPositionOpenTime(positionId);
      if(openTimeUtc <= 0)
      {
         skippedMissingOpen++;
         continue;
      }

      if(openTimeUtc < lowerUtc)
         continue;

      SyncDealRecord record;
      record.ticket = ticket;
      record.position_id = positionId;
      record.order_id = (ulong)HistoryDealGetInteger(ticket, DEAL_ORDER);
      record.symbol = HistoryDealGetString(ticket, DEAL_SYMBOL);
      record.entry = HistoryDealGetInteger(ticket, DEAL_ENTRY);
      record.type = HistoryDealGetInteger(ticket, DEAL_TYPE);
      record.volume = HistoryDealGetDouble(ticket, DEAL_VOLUME);
      record.price = HistoryDealGetDouble(ticket, DEAL_PRICE);
      record.profit = HistoryDealGetDouble(ticket, DEAL_PROFIT);
      record.swap = HistoryDealGetDouble(ticket, DEAL_SWAP);
      record.commission = HistoryDealGetDouble(ticket, DEAL_COMMISSION);
      record.magic = HistoryDealGetInteger(ticket, DEAL_MAGIC);
      record.comment = HistoryDealGetString(ticket, DEAL_COMMENT);
      record.open_time = openTimeUtc;
      record.deal_time = (long)HistoryDealGetInteger(ticket, DEAL_TIME) - g_gmtOffset;
      GetDealStopLevels(ticket, positionId, record.sl_price, record.tp_price);

      ArrayResize(records, count + 1);
      records[count] = record;
      count++;
   }

   if(skippedMissingOpen > 0)
      PrintFormat("[TradeSync][WARN] %d trade deal(s) skipped because the opening deal could not be found in %d days.",
                  skippedMissingOpen, OPEN_LOOKBACK_DAYS);

   if(count == 0)
   {
      Print("[TradeSync] No new trade deals. Cursor update is not required.");
      return(skippedMissingOpen == 0);
   }

   SortDeals(records, count);

   long maxOpenTime = 0;
   for(int i = 0; i < count; i++)
   {
      if(records[i].open_time > maxOpenTime)
         maxOpenTime = records[i].open_time;
   }

   const int batchSize = MathMax(1, MathMin(1000, Inp_MaxBatchSize));
   for(int offset = 0; offset < count; offset += batchSize)
   {
      string dealsJson = "";
      const int end = MathMin(count, offset + batchSize);
      for(int i = offset; i < end; i++)
      {
         if(StringLen(dealsJson) > 0)
            dealsJson += ",";
         dealsJson += DealToJson(records[i]);
      }

      string body = StringFormat(
         "{\"mt5_login\":%I64d,\"server_gmt_off\":0,\"deals\":[%s]}",
         GetLogin(), dealsJson);

      string response = "";
      if(!PostJson("/api/v1/ingest/deals", body, response))
         return(false);

      long accepted = 0, inserted = 0, duplicates = 0;
      JsonExtractLong(response, "accepted", accepted);
      JsonExtractLong(response, "inserted", inserted);
      JsonExtractLong(response, "duplicates", duplicates);
      PrintFormat("[TradeSync] Deals batch accepted=%d inserted=%I64d duplicates=%I64d",
                  end - offset, inserted, duplicates);
   }

   if(skippedMissingOpen > 0)
      return(false);

   return UpdateCursor(maxOpenTime);
}

bool BuildOpenTimeMap(const datetime fromServerTime, const datetime toServerTime)
{
   g_openMapCount = 0;
   ArrayResize(g_openPositionIds, 0);
   ArrayResize(g_openTimes, 0);

   if(!HistorySelect(fromServerTime, toServerTime))
   {
      PrintFormat("[TradeSync][ERROR] Opening deal HistorySelect failed error=%d", GetLastError());
      return(false);
   }

   const int total = HistoryDealsTotal();
   for(int i = 0; i < total; i++)
   {
      ulong ticket = HistoryDealGetTicket(i);
      if(ticket == 0)
         continue;

      long type = HistoryDealGetInteger(ticket, DEAL_TYPE);
      if(type != DEAL_TYPE_BUY && type != DEAL_TYPE_SELL)
         continue;

      long entry = HistoryDealGetInteger(ticket, DEAL_ENTRY);
      if(entry != DEAL_ENTRY_IN && entry != DEAL_ENTRY_INOUT)
         continue;

      ulong positionId = (ulong)HistoryDealGetInteger(ticket, DEAL_POSITION_ID);
      if(positionId == 0)
         continue;

      double volume = HistoryDealGetDouble(ticket, DEAL_VOLUME);
      double price = HistoryDealGetDouble(ticket, DEAL_PRICE);
      if(volume <= 0.0 || price <= 0.0)
         continue;

      long openTimeUtc = (long)HistoryDealGetInteger(ticket, DEAL_TIME) - g_gmtOffset;
      RememberPositionOpen(positionId, openTimeUtc);
   }

   return(true);
}

void RememberPositionOpen(const ulong positionId, const long openTimeUtc)
{
   for(int i = 0; i < g_openMapCount; i++)
   {
      if(g_openPositionIds[i] == positionId)
      {
         if(openTimeUtc < g_openTimes[i])
            g_openTimes[i] = openTimeUtc;
         return;
      }
   }

   ArrayResize(g_openPositionIds, g_openMapCount + 1);
   ArrayResize(g_openTimes, g_openMapCount + 1);
   g_openPositionIds[g_openMapCount] = positionId;
   g_openTimes[g_openMapCount] = openTimeUtc;
   g_openMapCount++;
}

long FindPositionOpenTime(const ulong positionId)
{
   for(int i = 0; i < g_openMapCount; i++)
   {
      if(g_openPositionIds[i] == positionId)
         return(g_openTimes[i]);
   }
   return(0);
}

bool UpdateCursor(const long maxOpenTime)
{
   if(maxOpenTime <= 0)
      return(true);

   string body = StringFormat(
      "{\"mt5_login\":%I64d,\"last_sync_time\":%I64d}",
      GetLogin(), maxOpenTime);
   string response = "";

   if(!PostJson("/api/v1/sync/update_last_sync_time", body, response))
      return(false);

   long serverCursor = 0;
   if(JsonExtractLong(response, "last_sync_time", serverCursor))
      g_serverCursor = serverCursor;

   PrintFormat("[TradeSync] Two-phase commit complete. last_sync_time=%I64d", g_serverCursor);
   return(true);
}

bool IsTradeDeal(const ulong ticket)
{
   const long dealType = HistoryDealGetInteger(ticket, DEAL_TYPE);
   if(dealType != DEAL_TYPE_BUY && dealType != DEAL_TYPE_SELL)
      return(false);

   const long entryType = HistoryDealGetInteger(ticket, DEAL_ENTRY);
   if(entryType != DEAL_ENTRY_IN &&
      entryType != DEAL_ENTRY_OUT &&
      entryType != DEAL_ENTRY_INOUT &&
      entryType != DEAL_ENTRY_OUT_BY)
      return(false);

   const string symbol = HistoryDealGetString(ticket, DEAL_SYMBOL);
   if(StringLen(symbol) == 0)
      return(false);

   const double volume = HistoryDealGetDouble(ticket, DEAL_VOLUME);
   const double price = HistoryDealGetDouble(ticket, DEAL_PRICE);
   if(volume <= 0.0 || price <= 0.0)
      return(false);

   return(true);
}

string DealToJson(const SyncDealRecord &record)
{
   return(StringFormat(
      "{\"ticket\":%I64u,\"position_id\":%I64u,\"order_id\":%I64u,"\
      "\"symbol\":\"%s\",\"entry\":%I64d,\"type\":%I64d,\"volume\":%s,\"price\":%s,"\
      "\"sl_price\":%s,\"tp_price\":%s,\"profit\":%s,\"swap\":%s,\"commission\":%s,"\
      "\"magic\":%I64d,\"comment\":\"%s\",\"open_time\":%I64d,\"deal_time\":%I64d}",
      record.ticket, record.position_id, record.order_id,
      JsonString(record.symbol), record.entry, record.type,
      DoubleToJson(record.volume), DoubleToJson(record.price),
      DoubleToJson(record.sl_price), DoubleToJson(record.tp_price),
      DoubleToJson(record.profit), DoubleToJson(record.swap), DoubleToJson(record.commission),
      record.magic, JsonString(record.comment), record.open_time, record.deal_time));
}

void GetDealStopLevels(const ulong ticket, const ulong positionId, double &sl, double &tp)
{
   sl = 0.0;
   tp = 0.0;

   const ulong orderTicket = (ulong)HistoryDealGetInteger(ticket, DEAL_ORDER);
   if(orderTicket != 0)
   {
      sl = NormalizeZero(HistoryOrderGetDouble(orderTicket, ORDER_SL));
      tp = NormalizeZero(HistoryOrderGetDouble(orderTicket, ORDER_TP));
      if(sl > 0.0 || tp > 0.0)
         return;
   }

   if(PositionSelectByTicket(positionId))
   {
      sl = NormalizeZero(PositionGetDouble(POSITION_SL));
      tp = NormalizeZero(PositionGetDouble(POSITION_TP));
      if(sl > 0.0 || tp > 0.0)
         return;
   }

   const long thisEntry = HistoryDealGetInteger(ticket, DEAL_ENTRY);
   if(thisEntry == DEAL_ENTRY_OUT || thisEntry == DEAL_ENTRY_OUT_BY || thisEntry == DEAL_ENTRY_INOUT)
   {
      const int totalDeals = HistoryDealsTotal();
      for(int i = 0; i < totalDeals; i++)
      {
         ulong otherTicket = HistoryDealGetTicket(i);
         if(otherTicket == 0)
            continue;
         if((ulong)HistoryDealGetInteger(otherTicket, DEAL_POSITION_ID) != positionId)
            continue;

         long otherEntry = HistoryDealGetInteger(otherTicket, DEAL_ENTRY);
         if(otherEntry != DEAL_ENTRY_IN && otherEntry != DEAL_ENTRY_INOUT)
            continue;

         ulong otherOrder = (ulong)HistoryDealGetInteger(otherTicket, DEAL_ORDER);
         if(otherOrder != 0)
         {
            sl = NormalizeZero(HistoryOrderGetDouble(otherOrder, ORDER_SL));
            tp = NormalizeZero(HistoryOrderGetDouble(otherOrder, ORDER_TP));
            return;
         }
      }
   }
}

void SortDeals(SyncDealRecord &records[], const int count)
{
   for(int i = 1; i < count; i++)
   {
      SyncDealRecord key = records[i];
      int j = i - 1;
      while(j >= 0 && DealEarlier(records[j], key))
      {
         records[j + 1] = records[j];
         j--;
      }
      records[j + 1] = key;
   }
}

bool DealEarlier(const SyncDealRecord &a, const SyncDealRecord &b)
{
   if(a.open_time != b.open_time)
      return(a.open_time > b.open_time);
   if(a.deal_time != b.deal_time)
      return(a.deal_time > b.deal_time);
   return(a.ticket > b.ticket);
}

void SendSymbolSpecsDue()
{
   const long nowUtc = (long)TimeGMT();
   if(g_lastSymbolSendUtc != 0 && nowUtc - g_lastSymbolSendUtc < SYMBOL_SPEC_INTERVAL_SEC)
      return;

   string names[];
   int count = 0;

   for(int i = 0; i < HistoryDealsTotal() && count < 1000; i++)
   {
      ulong ticket = HistoryDealGetTicket(i);
      if(ticket != 0)
         AddSymbolName(names, count, HistoryDealGetString(ticket, DEAL_SYMBOL));
   }

   const int selectedTotal = SymbolsTotal(true);
   for(int i = 0; i < selectedTotal && count < 1000; i++)
      AddSymbolName(names, count, SymbolName(i, true));

   int validCount = 0;
   for(int i = 0; i < count; i++)
   {
      if(IsValidSymbolSpec(names[i]))
      {
         names[validCount] = names[i];
         validCount++;
      }
   }

   if(validCount == 0)
   {
      Print("[TradeSync][WARN] No valid symbol specifications are available yet.");
      return;
   }

   for(int offset = 0; offset < validCount; offset += 1000)
   {
      string itemsJson = "";
      const int end = MathMin(validCount, offset + 1000);
      for(int i = offset; i < end; i++)
      {
         if(StringLen(itemsJson) > 0)
            itemsJson += ",";
         itemsJson += SymbolToJson(names[i]);
      }

      string body = StringFormat("{\"mt5_login\":%I64d,\"symbols\":[%s]}", GetLogin(), itemsJson);
      string response = "";
      if(!PostJson("/api/v1/ingest/symbols", body, response))
         return;

      long accepted = 0;
      JsonExtractLong(response, "accepted", accepted);
      if(accepted != (end - offset))
      {
         PrintFormat("[TradeSync][ERROR] Symbol accepted count mismatch: %s", response);
         return;
      }
   }

   g_lastSymbolSendUtc = nowUtc;
   PrintFormat("[TradeSync] Symbol specifications accepted: %d", validCount);
}

bool IsValidSymbolSpec(const string name)
{
   if(StringLen(name) == 0 || StringLen(name) > 50)
      return(false);
   const long digits = SymbolInfoInteger(name, SYMBOL_DIGITS);
   const double point = SymbolInfoDouble(name, SYMBOL_POINT);
   const double tickValue = SymbolInfoDouble(name, SYMBOL_TRADE_TICK_VALUE);
   const double contractSize = SymbolInfoDouble(name, SYMBOL_TRADE_CONTRACT_SIZE);
   return(digits >= 0 && digits <= 8 && point > 0.0 && tickValue > 0.0 && contractSize > 0.0);
}

string SymbolToJson(const string name)
{
   const long digits = SymbolInfoInteger(name, SYMBOL_DIGITS);
   return(StringFormat(
      "{\"name\":\"%s\",\"digits\":%I64d,\"point\":%s,\"tick_value\":%s,\"contract_size\":%s}",
      JsonString(name), digits,
      DoubleToJson(SymbolInfoDouble(name, SYMBOL_POINT)),
      DoubleToJson(SymbolInfoDouble(name, SYMBOL_TRADE_TICK_VALUE)),
      DoubleToJson(SymbolInfoDouble(name, SYMBOL_TRADE_CONTRACT_SIZE))));
}

void AddSymbolName(string &names[], int &count, const string name)
{
   if(StringLen(name) == 0 || StringLen(name) > 50)
      return;

   for(int i = 0; i < count; i++)
   {
      if(names[i] == name)
         return;
   }

   ArrayResize(names, count + 1);
   names[count] = name;
   count++;
}

void SendSnapshotDue()
{
   const long nowUtc = (long)TimeGMT();
   const int interval = MathMax(1, Inp_SnapshotIntervalSec);
   if(g_lastSnapshotUtc != 0 && nowUtc - g_lastSnapshotUtc < interval)
      return;

   string body = StringFormat(
      "{\"mt5_login\":%I64d,\"snapshots\":[{"\
      "\"balance\":%s,\"equity\":%s,\"margin\":%s,\"free_margin\":%s,\"snapshot_time\":%I64d}]}",
      GetLogin(),
      DoubleToJson(AccountInfoDouble(ACCOUNT_BALANCE)),
      DoubleToJson(AccountInfoDouble(ACCOUNT_EQUITY)),
      DoubleToJson(AccountInfoDouble(ACCOUNT_MARGIN)),
      DoubleToJson(AccountInfoDouble(ACCOUNT_MARGIN_FREE)),
      nowUtc);

   string response = "";
   if(!PostJson("/api/v1/ingest/snapshots", body, response))
      return;

   long accepted = 0;
   if(!JsonExtractLong(response, "accepted", accepted) || accepted < 1)
   {
      PrintFormat("[TradeSync][ERROR] Snapshot not accepted: %s", response);
      return;
   }

   g_lastSnapshotUtc = nowUtc;
   Print("[TradeSync] Account snapshot sent.");
}

void SendHeartbeatDue()
{
   const long nowUtc = (long)TimeGMT();
   const int interval = MathMax(1, Inp_HeartbeatIntervalSec);
   if(g_lastHeartbeatUtc != 0 && nowUtc - g_lastHeartbeatUtc < interval)
      return;

   string body = StringFormat(
      "{\"mt5_login\":%I64d,\"server_gmt_offset\":%I64d,\"server_timezone_name\":\"%s\"}",
      GetLogin(), g_gmtOffset, JsonString(FormatTimezoneName(g_gmtOffset)));
   string response = "";
   if(!PostJson("/api/v1/ingest/heartbeat", body, response))
      return;

   bool ok = false;
   if(!JsonExtractBool(response, "ok", ok) || !ok)
   {
      PrintFormat("[TradeSync][ERROR] Heartbeat rejected: %s", response);
      return;
   }

   g_lastHeartbeatUtc = nowUtc;
   Print("[TradeSync] Heartbeat sent.");
}

bool PostJson(const string path, const string body, string &response)
{
   response = "";
   const string url = g_baseUrl + path;
   const long timestamp = (long)TimeGMT();
   const string signature = HmacSha256Hex(Inp_SecretKey, body + IntegerToString(timestamp));

   const string headers =
      "Content-Type: application/json\r\n" +
      "Authorization: Bearer " + Inp_SecretKey + "\r\n" +
      "X-Timestamp: " + IntegerToString(timestamp) + "\r\n" +
      "X-Signature: " + signature + "\r\n";

   uchar requestData[];
   uchar responseData[];
   string responseHeaders = "";
   int requestSize = StringToCharArray(body, requestData, 0, WHOLE_ARRAY, CP_UTF8);
   if(requestSize > 0 && requestData[requestSize - 1] == 0)
      requestSize--;
   ArrayResize(requestData, requestSize);

   ResetLastError();
   const int httpCode = WebRequest("POST", url, headers, 10000,
                                   requestData, responseData, responseHeaders);
   if(httpCode == -1)
   {
      PrintFormat("[TradeSync][ERROR] WebRequest failed url=%s error=%d. Add the HTTPS URL to MT5 Tools > Options > Expert Advisors > Allow WebRequest.",
                  url, GetLastError());
      return(false);
   }

   response = CharArrayToString(responseData, 0, ArraySize(responseData), CP_UTF8);
   if(httpCode < 200 || httpCode >= 300)
   {
      PrintFormat("[TradeSync][ERROR] HTTP %d url=%s response=%s", httpCode, url, response);
      return(false);
   }

   return(true);
}

string HmacSha256Hex(const string secret, const string message)
{
   uchar keyBytes[];
   uchar messageBytes[];
   StringToUtf8(secret, keyBytes);
   StringToUtf8(message, messageBytes);

   if(ArraySize(keyBytes) > 64)
      ComputeSha256(keyBytes, keyBytes);

   uchar ipad[64];
   uchar opad[64];
   for(int i = 0; i < 64; i++)
   {
      uchar keyByte = (i < ArraySize(keyBytes)) ? keyBytes[i] : 0;
      ipad[i] = keyByte ^ 0x36;
      opad[i] = keyByte ^ 0x5c;
   }

   uchar innerInput[];
   AppendBytes(innerInput, ipad);
   AppendBytes(innerInput, messageBytes);

   uchar innerHash[];
   ComputeSha256(innerInput, innerHash);

   uchar outerInput[];
   AppendBytes(outerInput, opad);
   AppendBytes(outerInput, innerHash);

   uchar digest[];
   ComputeSha256(outerInput, digest);
   return(BytesToHex(digest));
}

void ComputeSha256(const uchar &source[], uchar &hash[])
{
   uchar emptyKey[];
   ArrayResize(hash, 32);
   ResetLastError();
   if(!CryptEncode(CRYPT_HASH_SHA256, source, emptyKey, hash))
   {
      PrintFormat("[TradeSync][ERROR] SHA256 failed error=%d", GetLastError());
      ArrayResize(hash, 0);
      return;
   }
   ArrayResize(hash, 32);
}

void AppendBytes(uchar &dst[], const uchar &src[])
{
   const int oldSize = ArraySize(dst);
   const int srcSize = ArraySize(src);
   ArrayResize(dst, oldSize + srcSize);
   for(int i = 0; i < srcSize; i++)
      dst[oldSize + i] = src[i];
}

bool StringToUtf8(const string value, uchar &bytes[])
{
   int length = (int)StringToCharArray(value, bytes, 0, WHOLE_ARRAY, CP_UTF8);
   if(length > 0 && bytes[length - 1] == 0)
      length--;
   ArrayResize(bytes, length);
   return(true);
}

string BytesToHex(const uchar &bytes[])
{
   string result = "";
   for(int i = 0; i < ArraySize(bytes); i++)
      result += StringFormat("%02x", bytes[i]);
   return(result);
}

string FormatTimezoneName(const long offsetSeconds)
{
   const long absSeconds = MathAbs(offsetSeconds);
   const long hours = absSeconds / 3600;
   const long minutes = (absSeconds % 3600) / 60;
   const string sign = (offsetSeconds < 0) ? "-" : "+";
   if(minutes == 0)
      return(StringFormat("UTC%s%I64d", sign, hours));
   return(StringFormat("UTC%s%I64d:%02I64d", sign, hours, minutes));
}

long GetLogin()
{
   return((long)AccountInfoInteger(ACCOUNT_LOGIN));
}

double NormalizeZero(const double value)
{
   if(value < 0.0 && value > -0.000000001)
      return(0.0);
   return(value);
}

string DoubleToJson(const double value)
{
   return(DoubleToString(NormalizeZero(value), 8));
}

string JsonString(const string value)
{
   string escaped = value;
   StringReplace(escaped, "\\", "\\\\");
   StringReplace(escaped, "\"", "\\\"");
   StringReplace(escaped, "\r", "\\r");
   StringReplace(escaped, "\n", "\\n");
   StringReplace(escaped, "\t", "\\t");

   string result = "";
   const int length = StringLen(escaped);
   for(int i = 0; i < length; i++)
   {
      ushort ch = StringGetCharacter(escaped, i);
      if(ch < 32)
         result += StringFormat("\\u%04x", ch);
      else
         result += ShortToString(ch);
   }

   return(result);
}

bool JsonExtractLong(const string json, const string key, long &value)
{
   value = 0;
   const string pattern = "\"" + key + "\"";
   int pos = StringFind(json, pattern);
   if(pos < 0)
      return(false);

   pos = StringFind(json, ":", pos + StringLen(pattern));
   if(pos < 0)
      return(false);

   pos++;
   const int length = StringLen(json);
   while(pos < length && StringGetCharacter(json, pos) == ' ')
      pos++;

   int start = pos;
   if(pos < length && StringGetCharacter(json, pos) == '-')
      pos++;

   while(pos < length)
   {
      ushort ch = StringGetCharacter(json, pos);
      if(ch < '0' || ch > '9')
         break;
      pos++;
   }

   if(pos == start || (pos == start + 1 && StringGetCharacter(json, start) == '-'))
      return(false);

   value = StringToInteger(StringSubstr(json, start, pos - start));
   return(true);
}

bool JsonExtractBool(const string json, const string key, bool &value)
{
   value = false;
   const string pattern = "\"" + key + "\"";
   int pos = StringFind(json, pattern);
   if(pos < 0)
      return(false);

   pos = StringFind(json, ":", pos + StringLen(pattern));
   if(pos < 0)
      return(false);

   pos++;
   const int length = StringLen(json);
   while(pos < length && StringGetCharacter(json, pos) == ' ')
      pos++;

   if(StringSubstr(json, pos, 4) == "true")
   {
      value = true;
      return(true);
   }

   if(StringSubstr(json, pos, 5) == "false")
   {
      value = false;
      return(true);
   }

   return(false);
}

string TrimTrailingSlash(string url)
{
   while(StringLen(url) > 0 && StringGetCharacter(url, StringLen(url) - 1) == '/')
      url = StringSubstr(url, 0, StringLen(url) - 1);
   return(url);
}
//+------------------------------------------------------------------+
