-- TradeSync PostgreSQL 18 baseline.
CREATE OR REPLACE FUNCTION now_iso() RETURNS text LANGUAGE sql STABLE AS $$
    SELECT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
$$;
CREATE OR REPLACE FUNCTION instr(haystack text, needle text) RETURNS integer LANGUAGE sql IMMUTABLE AS $$
    SELECT COALESCE(NULLIF(strpos(haystack, needle), 0), 0)
$$;
CREATE TABLE IF NOT EXISTS alembic_version (version_num VARCHAR(128) NOT NULL PRIMARY KEY);


CREATE TABLE account_key_rotation_audits (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT NOT NULL,account_id BIGINT NOT NULL,
        mt5_login TEXT NOT NULL,old_prefix TEXT NOT NULL,new_prefix TEXT NOT NULL,
        source TEXT NOT NULL CHECK(source IN ('manual','reset_sync')),
        created_at TEXT NOT NULL DEFAULT (now_iso()));

CREATE TABLE account_maintenance_audits (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT NOT NULL,account_id BIGINT,
        mt5_login TEXT NOT NULL,action TEXT NOT NULL CHECK(action IN ('reset','delete')),
        reason TEXT NOT NULL,sync_start_time BIGINT,counts_json TEXT NOT NULL,
        created_at TEXT NOT NULL DEFAULT (now_iso()));

CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    mt5_login BIGINT NOT NULL UNIQUE,
    label TEXT,
    broker_server TEXT,
    platform TEXT NOT NULL DEFAULT 'mt5',
    broker_company TEXT,
    account_currency TEXT,
    server_gmt_off BIGINT,
    key_prefix TEXT NOT NULL UNIQUE,
    key_hash TEXT NOT NULL,
    key_revoked BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (now_iso()),
    last_seen_at TEXT
, last_sync_time BIGINT NOT NULL DEFAULT 0, key_encrypted TEXT, key_environment TEXT NOT NULL DEFAULT 'live', key_created_at TEXT, key_last_used_at TEXT, updated_at TEXT, server_timezone_name TEXT, status TEXT NOT NULL DEFAULT 'active', sync_start_time BIGINT NOT NULL DEFAULT 0, last_success_sync_at TEXT, resync_pending BIGINT NOT NULL DEFAULT 0, notes TEXT, config_revision BIGINT NOT NULL DEFAULT 0);

CREATE TABLE api_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TEXT NOT NULL DEFAULT (now_iso()),
    user_id BIGINT,
    account_id BIGINT,
    mt5_login BIGINT,
    method TEXT NOT NULL,
    path TEXT NOT NULL,
    action TEXT NOT NULL DEFAULT '',
    status_code BIGINT NOT NULL,
    success BIGINT NOT NULL,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    item_count BIGINT,
    last_sync_time BIGINT,
    request_summary TEXT NOT NULL DEFAULT '{}',
    response_summary TEXT NOT NULL DEFAULT '{}',
    error_code TEXT,
    error_message TEXT,
    client_ip TEXT
, trace_id TEXT, sync_run_id BIGINT, batch_id TEXT, inserted_count BIGINT, updated_count BIGINT, duplicated_count BIGINT, rejected_count BIGINT);

CREATE TABLE auth_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    code_hash TEXT NOT NULL,
    purpose TEXT NOT NULL DEFAULT 'login',
    expires_at BIGINT NOT NULL,
    consumed BIGINT NOT NULL DEFAULT 0,
    attempts BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    consumed_at BIGINT
, delivery_status TEXT NOT NULL DEFAULT 'sent', test_mode BIGINT NOT NULL DEFAULT 0, request_ip_hash TEXT);

CREATE TABLE daily_review_versions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        review_id BIGINT NOT NULL,
        revision BIGINT NOT NULL,
        status TEXT NOT NULL,
        answers_json TEXT NOT NULL,
        summary_json TEXT NOT NULL,
        source_hash TEXT NOT NULL,
        created_at TEXT NOT NULL DEFAULT (now_iso()),
        UNIQUE(review_id,revision)
    );

CREATE TABLE daily_reviews (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL,
        account_id BIGINT NOT NULL,
        review_date TEXT NOT NULL,
        timezone TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','completed')),
        answers_json TEXT NOT NULL,
        summary_json TEXT NOT NULL,
        source_hash TEXT NOT NULL,
        revision BIGINT NOT NULL DEFAULT 1,
        first_completed_at TEXT,
        completed_at TEXT,
        created_at TEXT NOT NULL DEFAULT (now_iso()),
        updated_at TEXT NOT NULL DEFAULT (now_iso()),
        UNIQUE(user_id,account_id,review_date)
    );

CREATE TABLE day_plan_versions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        plan_id BIGINT NOT NULL,
        revision BIGINT NOT NULL,
        mode TEXT NOT NULL,
        status TEXT NOT NULL,
        content_json TEXT NOT NULL,
        change_reason TEXT NOT NULL DEFAULT '',
        created_at TEXT NOT NULL DEFAULT (now_iso()),
        UNIQUE(plan_id,revision)
    );

CREATE TABLE day_plans (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL,
        account_id BIGINT NOT NULL,
        plan_date TEXT NOT NULL,
        timezone TEXT NOT NULL,
        mode TEXT NOT NULL CHECK(mode IN ('trade','observe','rest')),
        status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','confirmed')),
        content_json TEXT NOT NULL,
        revision BIGINT NOT NULL DEFAULT 1,
        first_confirmed_at TEXT,
        confirmed_at TEXT,
        confirmed_late BIGINT NOT NULL DEFAULT 0,
        created_at TEXT NOT NULL DEFAULT (now_iso()),
        updated_at TEXT NOT NULL DEFAULT (now_iso()),
        UNIQUE(user_id,account_id,plan_date)
    );

CREATE TABLE deals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_login BIGINT NOT NULL,
    ticket BIGINT NOT NULL,
    position_id BIGINT,
    order_id BIGINT,
    symbol TEXT,
    entry BIGINT NOT NULL,
    type BIGINT NOT NULL,
    volume DOUBLE PRECISION NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    sl_price DOUBLE PRECISION,
    tp_price DOUBLE PRECISION,
    profit DOUBLE PRECISION NOT NULL DEFAULT 0,
    swap DOUBLE PRECISION NOT NULL DEFAULT 0,
    commission DOUBLE PRECISION NOT NULL DEFAULT 0,
    magic BIGINT NOT NULL DEFAULT 0,
    comment TEXT,
    deal_time BIGINT NOT NULL,
    server_gmt_off BIGINT,
    raw_json TEXT NOT NULL,
    received_at TEXT NOT NULL DEFAULT (now_iso()), open_time BIGINT NOT NULL DEFAULT 0,
    UNIQUE(account_login, ticket)
);

CREATE TABLE ea_instances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    instance_id TEXT NOT NULL,
    display_name TEXT,
    protocol_version TEXT,
    ea_version TEXT,
    last_seen_at TEXT,
    created_at TEXT NOT NULL DEFAULT (now_iso()),
    updated_at TEXT NOT NULL DEFAULT (now_iso()),
    UNIQUE(account_id, instance_id)
);

CREATE TABLE ea_settings_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_login BIGINT NOT NULL,
    snapshot_time BIGINT NOT NULL,
    settings_json TEXT NOT NULL,
    group_count BIGINT NOT NULL DEFAULT 0,
    key_count BIGINT NOT NULL DEFAULT 0,
    content_hash TEXT NOT NULL,
    raw_json TEXT NOT NULL,
    received_at BIGINT NOT NULL,
    UNIQUE(account_login, snapshot_time)
);

CREATE TABLE heartbeat_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_login BIGINT NOT NULL,
    timestamp BIGINT NOT NULL,
    version TEXT,
    received_at TEXT NOT NULL DEFAULT (now_iso())
);

CREATE TABLE heartbeats (
    account_login BIGINT PRIMARY KEY,
    server_gmt_off BIGINT,
    account_currency TEXT,
    broker_company TEXT,
    broker_server TEXT,
    ea_version TEXT,
    payload TEXT NOT NULL,
    last_seen_at TEXT NOT NULL DEFAULT (now_iso())
, server_gmt_offset BIGINT, server_timezone_name TEXT);

CREATE TABLE improvement_actions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT NOT NULL,weekly_review_id BIGINT,
        title TEXT NOT NULL,success_measure TEXT NOT NULL DEFAULT '',target_date TEXT,
        status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','completed','abandoned')),
        outcome TEXT NOT NULL DEFAULT '',revision BIGINT NOT NULL DEFAULT 1,
        created_at TEXT NOT NULL DEFAULT (now_iso()),
        updated_at TEXT NOT NULL DEFAULT (now_iso()));

CREATE TABLE intention_events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        intention_id BIGINT NOT NULL,
        from_state TEXT,
        to_state TEXT NOT NULL,
        reason TEXT NOT NULL DEFAULT '',
        source TEXT NOT NULL DEFAULT 'manual',
        created_at TEXT NOT NULL DEFAULT (now_iso())
    );

CREATE TABLE playbook_versions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        setup_id BIGINT NOT NULL,
        version BIGINT NOT NULL,
        status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','published')),
        revision BIGINT NOT NULL DEFAULT 0,
        content_json TEXT NOT NULL DEFAULT '{}',
        rules_json TEXT NOT NULL DEFAULT '[]',
        created_at TEXT NOT NULL DEFAULT (now_iso()),
        updated_at TEXT NOT NULL DEFAULT (now_iso()),
        published_at TEXT,
        UNIQUE(setup_id,version)
    );

CREATE TABLE reminders (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT NOT NULL,title TEXT NOT NULL,
        due_at TEXT,status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','done','snoozed')),
        snoozed_until TEXT,source_type TEXT NOT NULL DEFAULT 'manual',source_id BIGINT,
        revision BIGINT NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT (now_iso()),
        updated_at TEXT NOT NULL DEFAULT (now_iso()));

CREATE TABLE review_attachments (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        review_id BIGINT NOT NULL,
        data BYTEA NOT NULL,
        sha256 TEXT NOT NULL,
        size BIGINT NOT NULL,
        width BIGINT NOT NULL,
        height BIGINT NOT NULL,
        created_at TEXT NOT NULL DEFAULT (now_iso()),
        UNIQUE(review_id,sha256)
    );

CREATE TABLE review_evaluation_versions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        evaluation_id BIGINT NOT NULL,
        revision BIGINT NOT NULL,
        playbook_version_id BIGINT NOT NULL,
        answers_json TEXT NOT NULL,
        complete BIGINT NOT NULL,
        coverage DOUBLE PRECISION,
        score DOUBLE PRECISION,
        compliance TEXT NOT NULL,
        critical_failures_json TEXT NOT NULL,
        created_at TEXT NOT NULL DEFAULT (now_iso()),
        UNIQUE(evaluation_id,revision)
    );

CREATE TABLE review_evaluations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        review_id BIGINT NOT NULL UNIQUE,
        playbook_version_id BIGINT NOT NULL,
        answers_json TEXT NOT NULL DEFAULT '[]',
        complete BIGINT NOT NULL DEFAULT 0,
        coverage DOUBLE PRECISION,
        score DOUBLE PRECISION,
        compliance TEXT NOT NULL DEFAULT 'insufficient',
        critical_failures_json TEXT NOT NULL DEFAULT '[]',
        revision BIGINT NOT NULL DEFAULT 1,
        created_at TEXT NOT NULL DEFAULT (now_iso()),
        updated_at TEXT NOT NULL DEFAULT (now_iso())
    );

CREATE TABLE review_versions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        review_id BIGINT NOT NULL,
        revision BIGINT NOT NULL,
        status TEXT NOT NULL CHECK(status IN ('draft','reviewed')),
        notes TEXT NOT NULL,
        tags_json TEXT NOT NULL,
        source_hash TEXT NOT NULL,
        reflection_json TEXT NOT NULL DEFAULT '{}',
        created_at TEXT NOT NULL DEFAULT (now_iso()),
        UNIQUE(review_id, revision)
    );

CREATE TABLE setups (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL,
        name TEXT NOT NULL,
        description TEXT NOT NULL DEFAULT '',
        symbols_json TEXT NOT NULL DEFAULT '[]',
        directions_json TEXT NOT NULL DEFAULT '["buy","sell"]',
        status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','disabled')),
        created_at TEXT NOT NULL DEFAULT (now_iso()),
        updated_at TEXT NOT NULL DEFAULT (now_iso()),
        UNIQUE(user_id,name)
    );

CREATE TABLE snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_login BIGINT NOT NULL,
    timestamp BIGINT NOT NULL,
    balance DOUBLE PRECISION NOT NULL,
    equity DOUBLE PRECISION NOT NULL,
    margin DOUBLE PRECISION NOT NULL,
    free_margin DOUBLE PRECISION NOT NULL,
    margin_level DOUBLE PRECISION,
    raw_json TEXT NOT NULL,
    received_at TEXT NOT NULL DEFAULT (now_iso()),
    UNIQUE(account_login, timestamp)
);

CREATE TABLE symbols (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_login BIGINT NOT NULL,
    symbol TEXT NOT NULL,
    digits BIGINT NOT NULL,
    point DOUBLE PRECISION NOT NULL,
    contract_size DOUBLE PRECISION NOT NULL,
    tick_value DOUBLE PRECISION NOT NULL,
    tick_size DOUBLE PRECISION NOT NULL,
    currency_base TEXT NOT NULL,
    currency_profit TEXT NOT NULL,
    raw_json TEXT NOT NULL,
    updated_at TEXT NOT NULL DEFAULT (now_iso()),
    UNIQUE(account_login, symbol)
);

CREATE TABLE sync_batch_refs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_batch_id BIGINT NOT NULL,
    account_login BIGINT NOT NULL,
    deal_ticket BIGINT NOT NULL,
    deal_row_id BIGINT,
    created_at TEXT NOT NULL DEFAULT (now_iso()),
    UNIQUE(sync_batch_id, account_login, deal_ticket)
);

CREATE TABLE sync_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    sync_run_id BIGINT NOT NULL,
    batch_id TEXT NOT NULL,
    batch_index BIGINT NOT NULL,
    batch_count BIGINT NOT NULL,
    item_count BIGINT NOT NULL DEFAULT 0,
    inserted_count BIGINT NOT NULL DEFAULT 0,
    updated_count BIGINT NOT NULL DEFAULT 0,
    duplicated_count BIGINT NOT NULL DEFAULT 0,
    rejected_count BIGINT NOT NULL DEFAULT 0,
    request_hash TEXT,
    payload_hash TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'received',
    retries BIGINT NOT NULL DEFAULT 0,
    received_at TEXT NOT NULL DEFAULT (now_iso()),
    created_at TEXT NOT NULL DEFAULT (now_iso()),
    updated_at TEXT NOT NULL DEFAULT (now_iso()),
    UNIQUE(account_id, batch_id),
    UNIQUE(sync_run_id, batch_index)
);

CREATE TABLE sync_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    instance_id TEXT,
    protocol_version TEXT NOT NULL DEFAULT '2.1',
    status TEXT NOT NULL DEFAULT 'open',
    cursor_start BIGINT NOT NULL DEFAULT 0,
    cursor_end BIGINT,
    expected_batch_count BIGINT,
    received_batch_count BIGINT NOT NULL DEFAULT 0,
    expected_deal_count BIGINT,
    received_deal_count BIGINT NOT NULL DEFAULT 0,
    inserted_count BIGINT NOT NULL DEFAULT 0,
    updated_count BIGINT NOT NULL DEFAULT 0,
    duplicated_count BIGINT NOT NULL DEFAULT 0,
    rejected_count BIGINT NOT NULL DEFAULT 0,
    checksum TEXT,
    last_error TEXT,
    started_at TEXT NOT NULL DEFAULT (now_iso()),
    last_batch_at TEXT,
    committed_at TEXT,
    finished_at TEXT,
    created_at TEXT NOT NULL DEFAULT (now_iso()),
    updated_at TEXT NOT NULL DEFAULT (now_iso())
);

CREATE TABLE tag_definitions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT NOT NULL,name TEXT NOT NULL,
        group_name TEXT NOT NULL DEFAULT '未分组',status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','disabled')),
        revision BIGINT NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT (now_iso()),
        updated_at TEXT NOT NULL DEFAULT (now_iso()),UNIQUE(user_id,name));

CREATE TABLE trade_allocations (
        trade_id BIGINT NOT NULL,
        deal_ticket BIGINT NOT NULL,
        role TEXT NOT NULL,
        volume DOUBLE PRECISION NOT NULL,
        profit DOUBLE PRECISION NOT NULL,
        swap DOUBLE PRECISION NOT NULL,
        commission DOUBLE PRECISION NOT NULL,
        method TEXT NOT NULL,
        PRIMARY KEY(trade_id,deal_ticket,role)
    );

CREATE TABLE trade_dirty_positions (
        account_login BIGINT NOT NULL, position_id BIGINT NOT NULL,
        PRIMARY KEY(account_login,position_id)
    );

CREATE OR REPLACE FUNCTION trades_mark_dirty() RETURNS trigger
LANGUAGE plpgsql AS $function$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF COALESCE(OLD.position_id, 0) <> 0 THEN
            INSERT INTO trade_dirty_positions(account_login, position_id)
            VALUES (OLD.account_login, OLD.position_id)
            ON CONFLICT DO NOTHING;
        END IF;
        RETURN OLD;
    END IF;

    IF TG_OP = 'UPDATE'
       AND COALESCE(OLD.position_id, 0) <> 0
       AND (OLD.account_login, OLD.position_id) IS DISTINCT FROM (NEW.account_login, NEW.position_id) THEN
        INSERT INTO trade_dirty_positions(account_login, position_id)
        VALUES (OLD.account_login, OLD.position_id)
        ON CONFLICT DO NOTHING;
    END IF;

    IF COALESCE(NEW.position_id, 0) <> 0 THEN
        INSERT INTO trade_dirty_positions(account_login, position_id)
        VALUES (NEW.account_login, NEW.position_id)
        ON CONFLICT DO NOTHING;
    END IF;

    RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trades_dirty ON deals;
CREATE TRIGGER trades_dirty
AFTER INSERT OR UPDATE OR DELETE ON deals
FOR EACH ROW EXECUTE FUNCTION trades_mark_dirty();

CREATE TABLE trade_intentions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL,
        account_id BIGINT NOT NULL,
        day_plan_id BIGINT,
        scenario_id TEXT,
        playbook_version_id BIGINT,
        symbol TEXT NOT NULL,
        direction TEXT NOT NULL CHECK(direction IN ('buy','sell')),
        state TEXT NOT NULL CHECK(state IN ('watching','prepared','executed_unlinked','linked','abandoned','invalidated','expired')),
        entry_basis TEXT NOT NULL DEFAULT '',
        risk_plan TEXT NOT NULL DEFAULT '',
        linked_trade_id BIGINT UNIQUE,
        linked_at TEXT,
        created_at TEXT NOT NULL DEFAULT (now_iso()),
        updated_at TEXT NOT NULL DEFAULT (now_iso())
    );

CREATE TABLE trade_lifecycles (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        account_id BIGINT NOT NULL,
        position_id BIGINT NOT NULL,
        anchor_ticket BIGINT NOT NULL,
        symbol TEXT NOT NULL,
        direction TEXT NOT NULL,
        status TEXT NOT NULL CHECK(status IN ('complete','partial','needs_review')),
        open_time BIGINT,
        close_time BIGINT,
        payload_json TEXT NOT NULL,
        builder_version BIGINT NOT NULL DEFAULT 1,
        UNIQUE(account_id,position_id,anchor_ticket)
    );

CREATE TABLE trade_reconciliation_cases (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT NOT NULL,account_id BIGINT NOT NULL,
        position_id TEXT NOT NULL,anchor_ticket TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'open'
            CHECK(state IN ('open','investigating','resolved')),
        resolution TEXT CHECK(resolution IS NULL OR resolution IN ('source_confirmed','awaiting_resync','not_a_trade')),
        note TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT (now_iso()),
        updated_at TEXT NOT NULL DEFAULT (now_iso()),
        UNIQUE(user_id,account_id,position_id,anchor_ticket));

CREATE TABLE trade_reconciliation_events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,case_id BIGINT NOT NULL,state TEXT NOT NULL,
        resolution TEXT,note TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT (now_iso()));

CREATE TABLE trade_reviews (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        account_id BIGINT NOT NULL,
        position_id BIGINT NOT NULL,
        anchor_ticket BIGINT NOT NULL,
        status TEXT NOT NULL CHECK(status IN ('draft','reviewed')),
        notes TEXT NOT NULL DEFAULT '',
        tags_json TEXT NOT NULL DEFAULT '[]',
        source_hash TEXT NOT NULL,
        revision BIGINT NOT NULL DEFAULT 1,
        updated_at TEXT NOT NULL DEFAULT (now_iso()), reflection_json TEXT NOT NULL DEFAULT '{}',
        UNIQUE(account_id,position_id,anchor_ticket)
    );

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL DEFAULT (now_iso()),
    last_login_at TEXT
, phone TEXT);

CREATE TABLE IF NOT EXISTS user_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    namespace TEXT NOT NULL,
    payload TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (now_iso()),
    updated_at TEXT NOT NULL DEFAULT (now_iso()),
    UNIQUE(user_id, namespace)
);

CREATE TABLE weekly_reviews (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT NOT NULL,week_start TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','completed')),
        answers_json TEXT NOT NULL,summary_json TEXT NOT NULL,source_hash TEXT NOT NULL,
        revision BIGINT NOT NULL DEFAULT 1,completed_at TEXT,
        created_at TEXT NOT NULL DEFAULT (now_iso()),
        updated_at TEXT NOT NULL DEFAULT (now_iso()),UNIQUE(user_id,week_start));

CREATE TABLE workspace_settings (
        user_id BIGINT PRIMARY KEY,
        display_timezone TEXT NOT NULL DEFAULT 'Asia/Shanghai',
        trading_day_start TEXT NOT NULL DEFAULT '00:00',
        default_session TEXT NOT NULL DEFAULT '全天',
        revision BIGINT NOT NULL DEFAULT 1,
        created_at TEXT NOT NULL DEFAULT (now_iso()),
        updated_at TEXT NOT NULL DEFAULT (now_iso())
    );

ALTER TABLE account_key_rotation_audits ADD CONSTRAINT fk_account_key_rotation_audits_1 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE account_maintenance_audits ADD CONSTRAINT fk_account_maintenance_audits_2 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE accounts ADD CONSTRAINT fk_accounts_3 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE daily_review_versions ADD CONSTRAINT fk_daily_review_versions_4 FOREIGN KEY (review_id) REFERENCES daily_reviews(id) ON DELETE CASCADE;

ALTER TABLE daily_reviews ADD CONSTRAINT fk_daily_reviews_5 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE daily_reviews ADD CONSTRAINT fk_daily_reviews_6 FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE day_plan_versions ADD CONSTRAINT fk_day_plan_versions_7 FOREIGN KEY (plan_id) REFERENCES day_plans(id) ON DELETE CASCADE;

ALTER TABLE day_plans ADD CONSTRAINT fk_day_plans_8 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE day_plans ADD CONSTRAINT fk_day_plans_9 FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE ea_instances ADD CONSTRAINT fk_ea_instances_10 FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE improvement_actions ADD CONSTRAINT fk_improvement_actions_11 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE improvement_actions ADD CONSTRAINT fk_improvement_actions_12 FOREIGN KEY (weekly_review_id) REFERENCES weekly_reviews(id) ON DELETE SET NULL;

ALTER TABLE intention_events ADD CONSTRAINT fk_intention_events_13 FOREIGN KEY (intention_id) REFERENCES trade_intentions(id) ON DELETE CASCADE;

ALTER TABLE playbook_versions ADD CONSTRAINT fk_playbook_versions_14 FOREIGN KEY (setup_id) REFERENCES setups(id) ON DELETE CASCADE;

ALTER TABLE reminders ADD CONSTRAINT fk_reminders_15 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE review_attachments ADD CONSTRAINT fk_review_attachments_16 FOREIGN KEY (review_id) REFERENCES trade_reviews(id) ON DELETE CASCADE;

ALTER TABLE review_evaluation_versions ADD CONSTRAINT fk_review_evaluation_versions_17 FOREIGN KEY (evaluation_id) REFERENCES review_evaluations(id) ON DELETE CASCADE;

ALTER TABLE review_evaluation_versions ADD CONSTRAINT fk_review_evaluation_versions_18 FOREIGN KEY (playbook_version_id) REFERENCES playbook_versions(id);

ALTER TABLE review_evaluations ADD CONSTRAINT fk_review_evaluations_19 FOREIGN KEY (review_id) REFERENCES trade_reviews(id) ON DELETE CASCADE;

ALTER TABLE review_evaluations ADD CONSTRAINT fk_review_evaluations_20 FOREIGN KEY (playbook_version_id) REFERENCES playbook_versions(id);

ALTER TABLE review_versions ADD CONSTRAINT fk_review_versions_21 FOREIGN KEY (review_id) REFERENCES trade_reviews(id) ON DELETE CASCADE;

ALTER TABLE setups ADD CONSTRAINT fk_setups_22 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE sync_batch_refs ADD CONSTRAINT fk_sync_batch_refs_23 FOREIGN KEY (sync_batch_id) REFERENCES sync_batches(id) ON DELETE CASCADE;

ALTER TABLE sync_batch_refs ADD CONSTRAINT fk_sync_batch_refs_24 FOREIGN KEY (deal_row_id) REFERENCES deals(id) ON DELETE CASCADE;

ALTER TABLE sync_batches ADD CONSTRAINT fk_sync_batches_25 FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE sync_batches ADD CONSTRAINT fk_sync_batches_26 FOREIGN KEY (sync_run_id) REFERENCES sync_runs(id) ON DELETE CASCADE;

ALTER TABLE sync_runs ADD CONSTRAINT fk_sync_runs_27 FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE tag_definitions ADD CONSTRAINT fk_tag_definitions_28 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE trade_allocations ADD CONSTRAINT fk_trade_allocations_29 FOREIGN KEY (trade_id) REFERENCES trade_lifecycles(id) ON DELETE CASCADE;

ALTER TABLE trade_intentions ADD CONSTRAINT fk_trade_intentions_30 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE trade_intentions ADD CONSTRAINT fk_trade_intentions_31 FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE trade_intentions ADD CONSTRAINT fk_trade_intentions_32 FOREIGN KEY (day_plan_id) REFERENCES day_plans(id) ON DELETE SET NULL;

ALTER TABLE trade_intentions ADD CONSTRAINT fk_trade_intentions_33 FOREIGN KEY (playbook_version_id) REFERENCES playbook_versions(id);

ALTER TABLE trade_intentions ADD CONSTRAINT fk_trade_intentions_34 FOREIGN KEY (linked_trade_id) REFERENCES trade_lifecycles(id) ON DELETE SET NULL;

ALTER TABLE trade_lifecycles ADD CONSTRAINT fk_trade_lifecycles_35 FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE trade_reconciliation_cases ADD CONSTRAINT fk_trade_reconciliation_cases_36 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE trade_reconciliation_cases ADD CONSTRAINT fk_trade_reconciliation_cases_37 FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE trade_reconciliation_events ADD CONSTRAINT fk_trade_reconciliation_events_38 FOREIGN KEY (case_id) REFERENCES trade_reconciliation_cases(id) ON DELETE CASCADE;

ALTER TABLE trade_reviews ADD CONSTRAINT fk_trade_reviews_39 FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE weekly_reviews ADD CONSTRAINT fk_weekly_reviews_40 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE workspace_settings ADD CONSTRAINT fk_workspace_settings_41 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_account_maintenance_audits_user_time ON account_maintenance_audits(user_id,created_at DESC);

CREATE INDEX IF NOT EXISTS idx_accounts_last_sync_time ON accounts(last_sync_time);

CREATE INDEX IF NOT EXISTS idx_accounts_status ON accounts(status);

CREATE INDEX IF NOT EXISTS idx_accounts_user ON accounts(user_id);

CREATE INDEX IF NOT EXISTS idx_api_logs_account_time ON api_logs(account_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_api_logs_created ON api_logs(created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_api_logs_login_time ON api_logs(mt5_login, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_api_logs_sync_run ON api_logs(sync_run_id);

CREATE INDEX IF NOT EXISTS idx_api_logs_trace ON api_logs(trace_id);

CREATE INDEX IF NOT EXISTS idx_api_logs_user_time ON api_logs(user_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_attachments_review ON review_attachments(review_id);

CREATE INDEX IF NOT EXISTS idx_auth_codes_email_time
    ON auth_codes(email, created_at);

CREATE INDEX IF NOT EXISTS idx_auth_codes_ip_time ON auth_codes(request_ip_hash,created_at);

CREATE INDEX IF NOT EXISTS idx_auth_codes_time ON auth_codes(created_at);

CREATE INDEX IF NOT EXISTS idx_daily_reviews_user_date ON daily_reviews(user_id,review_date);

CREATE INDEX IF NOT EXISTS idx_day_plans_user_date ON day_plans(user_id,plan_date);

CREATE INDEX IF NOT EXISTS idx_deals_account_open_time ON deals(account_login, open_time);

CREATE INDEX IF NOT EXISTS idx_deals_account_position
    ON deals(account_login, position_id);

CREATE INDEX IF NOT EXISTS idx_deals_account_time
    ON deals(account_login, deal_time);

CREATE INDEX IF NOT EXISTS idx_ea_instances_account ON ea_instances(account_id);

CREATE INDEX IF NOT EXISTS idx_ea_settings_account_time
    ON ea_settings_history(account_login, snapshot_time DESC);

CREATE INDEX IF NOT EXISTS idx_heartbeat_history_account_time
    ON heartbeat_history(account_login, timestamp);

CREATE INDEX IF NOT EXISTS idx_heartbeat_history_time
    ON heartbeat_history(timestamp);

CREATE INDEX IF NOT EXISTS idx_improvement_actions_user_status ON improvement_actions(user_id,status);

CREATE INDEX IF NOT EXISTS idx_intentions_user_account_state ON trade_intentions(user_id,account_id,state);

CREATE INDEX IF NOT EXISTS idx_key_rotation_audits_user_time ON account_key_rotation_audits(user_id,created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_playbook_one_draft ON playbook_versions(setup_id) WHERE status='draft';

CREATE INDEX IF NOT EXISTS idx_reminders_user_status_due ON reminders(user_id,status,due_at);

CREATE INDEX IF NOT EXISTS idx_review_versions_review ON review_versions(review_id, revision DESC);

CREATE INDEX IF NOT EXISTS idx_reviews_account_updated ON trade_reviews(account_id,updated_at,id);

CREATE INDEX IF NOT EXISTS idx_setups_user_status ON setups(user_id,status);

CREATE INDEX IF NOT EXISTS idx_snapshots_account_time ON snapshots(account_login, timestamp);

CREATE INDEX IF NOT EXISTS idx_symbols_account ON symbols(account_login);

CREATE INDEX IF NOT EXISTS idx_sync_batch_refs_batch ON sync_batch_refs(sync_batch_id);

CREATE INDEX IF NOT EXISTS idx_sync_batch_refs_deal ON sync_batch_refs(account_login, deal_ticket);

CREATE INDEX IF NOT EXISTS idx_sync_batches_run ON sync_batches(sync_run_id, batch_index);

CREATE INDEX IF NOT EXISTS idx_sync_runs_account_started ON sync_runs(account_id, started_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_sync_runs_status ON sync_runs(status, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_tag_definitions_user_group ON tag_definitions(user_id,group_name,status);

CREATE INDEX IF NOT EXISTS idx_trade_case_events_case ON trade_reconciliation_events(case_id,id DESC);

CREATE INDEX IF NOT EXISTS idx_trade_cases_user_state ON trade_reconciliation_cases(user_id,state,updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_trades_account_close ON trade_lifecycles(account_id,close_time,id);

CREATE INDEX IF NOT EXISTS idx_trades_account_open ON trade_lifecycles(account_id,open_time,id);

CREATE INDEX IF NOT EXISTS idx_trades_account_status ON trade_lifecycles(account_id,status,id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_phone ON users(phone) WHERE phone IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_weekly_reviews_user_week ON weekly_reviews(user_id,week_start);

INSERT INTO alembic_version(version_num) VALUES ('0022_postgresql_baseline') ON CONFLICT DO NOTHING;
