CREATE TABLE connector_connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id TEXT NOT NULL UNIQUE,
    account_id BIGINT NOT NULL,
    platform TEXT NOT NULL,
    account_ref TEXT NOT NULL,
    instance_id TEXT,
    connector_version TEXT,
    protocol_version TEXT NOT NULL DEFAULT '1.0',
    capabilities_json TEXT NOT NULL DEFAULT '[]',
    status TEXT NOT NULL DEFAULT 'active',
    cursor_basis TEXT NOT NULL DEFAULT 'event_time',
    cursor_value BIGINT NOT NULL DEFAULT 0,
    cursor_state_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT (now_iso()),
    updated_at TEXT NOT NULL DEFAULT (now_iso()),
    UNIQUE(account_id, platform, account_ref, instance_id)
);

CREATE TABLE connector_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT NOT NULL,
    batch_id TEXT NOT NULL,
    batch_index BIGINT NOT NULL,
    batch_count BIGINT NOT NULL,
    idempotency_key TEXT,
    payload_hash TEXT NOT NULL,
    item_count BIGINT NOT NULL DEFAULT 0,
    inserted_count BIGINT NOT NULL DEFAULT 0,
    duplicate_count BIGINT NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'received',
    received_at TEXT NOT NULL DEFAULT (now_iso()),
    created_at TEXT NOT NULL DEFAULT (now_iso()),
    updated_at TEXT NOT NULL DEFAULT (now_iso()),
    UNIQUE(connection_id, batch_id)
);

CREATE TABLE connector_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT NOT NULL,
    event_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    occurred_at BIGINT NOT NULL DEFAULT 0,
    batch_id TEXT NOT NULL,
    payload JSONB NOT NULL,
    created_at TEXT NOT NULL DEFAULT (now_iso()),
    UNIQUE(connection_id, event_id, event_type)
);

CREATE INDEX idx_connector_events_connection_time
    ON connector_events(connection_id, occurred_at);
