ALTER TABLE deals
    ADD COLUMN IF NOT EXISTS server_open_time BIGINT,
    ADD COLUMN IF NOT EXISTS server_deal_time BIGINT,
    ADD COLUMN IF NOT EXISTS timezone_profile_id BIGINT,
    ADD COLUMN IF NOT EXISTS time_normalized_at TEXT;

CREATE TABLE IF NOT EXISTS broker_timezone_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_type TEXT NOT NULL,
    match_value TEXT NOT NULL,
    timezone_name TEXT,
    fixed_offset_seconds BIGINT,
    dst_profile TEXT NOT NULL DEFAULT 'none',
    confidence BIGINT NOT NULL DEFAULT 100,
    enabled BIGINT NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (now_iso()),
    updated_at TEXT NOT NULL DEFAULT (now_iso()),
    UNIQUE(match_type, match_value)
);

CREATE TABLE IF NOT EXISTS broker_timezone_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    broker_key TEXT NOT NULL UNIQUE,
    broker_server TEXT,
    broker_company TEXT,
    platform TEXT NOT NULL DEFAULT 'mt5',
    observed_offset_seconds BIGINT,
    first_seen_at TEXT NOT NULL DEFAULT (now_iso()),
    last_seen_at TEXT NOT NULL DEFAULT (now_iso()),
    observation_count BIGINT NOT NULL DEFAULT 1,
    transition_count BIGINT NOT NULL DEFAULT 0,
    inferred_timezone TEXT,
    confidence BIGINT NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'observing'
);

INSERT INTO broker_timezone_profiles (
    match_type, match_value, timezone_name, dst_profile, confidence
) VALUES
    ('pattern', '%XMGlobal%', 'Europe/Athens', 'eu', 95),
    ('pattern', '%MetaQuotes-Demo%', 'Europe/Athens', 'eu', 90)
ON CONFLICT(match_type, match_value) DO NOTHING;
