CREATE TABLE IF NOT EXISTS closed_trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket BIGINT NOT NULL,
    account_login BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    position_id BIGINT NOT NULL,
    symbol TEXT,
    type BIGINT NOT NULL,
    volume DOUBLE PRECISION NOT NULL,
    close_price DOUBLE PRECISION NOT NULL,
    sl_price DOUBLE PRECISION,
    tp_price DOUBLE PRECISION,
    profit DOUBLE PRECISION NOT NULL DEFAULT 0,
    swap DOUBLE PRECISION NOT NULL DEFAULT 0,
    commission DOUBLE PRECISION NOT NULL DEFAULT 0,
    magic BIGINT NOT NULL DEFAULT 0,
    comment TEXT,
    open_time BIGINT NOT NULL DEFAULT 0,
    deal_time BIGINT NOT NULL,
    open_price DOUBLE PRECISION,
    point DOUBLE PRECISION,
    contract_size DOUBLE PRECISION,
    UNIQUE(account_login, position_id)
);

CREATE INDEX IF NOT EXISTS idx_closed_trades_account_deal_time
    ON closed_trades(account_login, deal_time);

CREATE INDEX IF NOT EXISTS idx_closed_trades_account_id
    ON closed_trades(account_id);

CREATE OR REPLACE FUNCTION rebuild_closed_trades_for_login(p_login BIGINT)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    DELETE FROM closed_trades WHERE account_login = p_login;

    INSERT INTO closed_trades (
        ticket, account_login, account_id, position_id, symbol, type, volume,
        close_price, sl_price, tp_price, profit, swap, commission, magic, comment,
        open_time, deal_time, open_price, point, contract_size
    )
    SELECT
        min(d.ticket) AS ticket,
        d.account_login,
        a.id AS account_id,
        d.position_id,
        max(d.symbol) AS symbol,
        COALESCE(in_.type, max(d.type)) AS type,
        sum(d.volume) AS volume,
        round((sum(d.volume * d.price) / NULLIF(sum(d.volume), 0))::numeric, 6) AS close_price,
        max(d.sl_price) AS sl_price,
        max(d.tp_price) AS tp_price,
        sum(d.profit) AS profit,
        sum(d.swap) AS swap,
        sum(d.commission) AS commission,
        max(d.magic) AS magic,
        max(d.comment) AS comment,
        min(d.open_time) AS open_time,
        max(d.deal_time) AS deal_time,
        in_.price AS open_price,
        s.point,
        s.contract_size
      FROM deals d
      JOIN accounts a ON a.mt5_login = d.account_login
      LEFT JOIN symbols s ON s.account_login = d.account_login AND s.symbol = d.symbol
      LEFT JOIN LATERAL (
          SELECT min(i.type) AS type,
                 round((sum(i.volume * i.price) / NULLIF(sum(i.volume), 0))::numeric, 6) AS price
            FROM deals i
           WHERE i.account_login = d.account_login
             AND i.position_id = d.position_id
             AND i.entry = 0
      ) in_ ON TRUE
     WHERE d.entry = 1
       AND d.account_login = p_login
       AND d.position_id IS NOT NULL
     GROUP BY
        d.account_login,
        d.position_id,
        in_.type,
        in_.price,
        s.point,
        s.contract_size,
        a.id;
END;
$function$;

CREATE OR REPLACE FUNCTION refresh_closed_trades()
RETURNS void
LANGUAGE plpgsql
AS $function$
DECLARE
    dirty_account RECORD;
BEGIN
    FOR dirty_account IN
        SELECT DISTINCT account_login
          FROM trade_dirty_positions
    LOOP
        PERFORM rebuild_closed_trades_for_login(dirty_account.account_login);
    END LOOP;

    DELETE FROM trade_dirty_positions;
END;
$function$;

INSERT INTO trade_dirty_positions(account_login, position_id)
SELECT DISTINCT account_login, position_id
  FROM deals
 WHERE COALESCE(position_id, 0) <> 0
ON CONFLICT DO NOTHING;

SELECT refresh_closed_trades();
